[32mINFO    [0m test_add_new_user:test_add_new_user.py:20 ====== Started: 1722156245 ======
[35mDEBUG   [0m test_add_new_user:test_add_new_user.py:22 Navigating to Main Page
[35mDEBUG   [0m test_add_new_user:test_add_new_user.py:25 Clicking My Account
[31m[1mERROR   [0m test_add_new_user:test_add_new_user.py:55 Error during test execution: Message: 
Stacktrace:
#0 0x64d4b2a1af83 <unknown>
#1 0x64d4b26d3cf7 <unknown>
#2 0x64d4b272399e <unknown>
#3 0x64d4b2723aa1 <unknown>
#4 0x64d4b276ed64 <unknown>
#5 0x64d4b274d0dd <unknown>
#6 0x64d4b276c006 <unknown>
#7 0x64d4b274ce53 <unknown>
#8 0x64d4b2714dd4 <unknown>
#9 0x64d4b27161de <unknown>
#10 0x64d4b29df531 <unknown>
#11 0x64d4b29e3455 <unknown>
#12 0x64d4b29cbf55 <unknown>
#13 0x64d4b29e40ef <unknown>
#14 0x64d4b29af99f <unknown>
#15 0x64d4b2a08008 <unknown>
#16 0x64d4b2a081d7 <unknown>
#17 0x64d4b2a1a124 <unknown>
#18 0x7ac6b0e94ac3 <unknown>