{"name": "test_login", "status": "broken", "statusDetails": {"message": "AttributeError: 'RegisterUser' object has no attribute 'input_data_first_name'", "trace": "browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"fba9dd2f016890ecb14b4ca88d2ff16b\")>\n\n    @pytest.mark.usefixtures(\"browser\")\n    def test_login(browser):\n        logger.info('====== Started: {} ======'.format(int(time.time())))\n        try:\n            with allure.step('Navigating to Main Page and clicking My Account'):\n                logger.debug('Navigating to Main Page')\n                main_page = MainPage(browser)\n                logger.debug('Clicking My Account')\n                main_page.click_my_account()\n                take_screenshot(browser, 'Main Page - My Account')\n    \n            with allure.step('Clicking Register User'):\n                logger.debug('Clicking Register User')\n                main_page.click_register_user()\n                take_screenshot(browser, 'Main Page - Register User')\n    \n            with allure.step('Filling registration form'):\n                logger.debug('Filling registration form')\n                register_user = RegisterUser(browser)\n>               register_user.input_data_first_name()\nE               AttributeError: 'RegisterUser' object has no attribute 'input_data_first_name'\n\ntests/test_login.py:42: AttributeError"}, "steps": [{"name": "Navigating to Main Page and clicking My Account", "status": "passed", "attachments": [{"name": "Main Page - My Account", "source": "4a7c25f3-f80e-4b50-88c4-72d5e6505b8e-attachment.png", "type": "image/png"}], "start": 1722156109858, "stop": 1722156110645}, {"name": "Clicking Register User", "status": "passed", "attachments": [{"name": "Main Page - Register User", "source": "7fd53188-97bf-4736-a71a-702e52e6544f-attachment.png", "type": "image/png"}], "start": 1722156110645, "stop": 1722156111578}, {"name": "Filling registration form", "status": "broken", "statusDetails": {"message": "AttributeError: 'RegisterUser' object has no attribute 'input_data_first_name'\n", "trace": "  File \"/home/we/Desktop/Projects/Python/pyOtus/tests/test_login.py\", line 42, in test_login\n    register_user.input_data_first_name()\n"}, "start": 1722156111578, "stop": 1722156111578}], "attachments": [{"name": "Error", "source": "813d4e14-93b1-4c06-96c2-5d96c4afc244-attachment.png", "type": "image/png"}, {"name": "log", "source": "6411b375-d1aa-4c2f-a993-94e8426b34fa-attachment.txt", "type": "text/plain"}], "start": 1722156109857, "stop": 1722156111704, "uuid": "5d0b7fea-8915-4547-a1d2-8bcfe9ce7982", "historyId": "a707b9555172d26c5c1ec2d556e674f3", "testCaseId": "a707b9555172d26c5c1ec2d556e674f3", "fullName": "tests.test_login#test_login", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('browser')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "we"}, {"name": "thread", "value": "8203-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}