{"name": "test_login", "status": "broken", "statusDetails": {"message": "AttributeError: 'RegisterUser' object has no attribute 'input_data_first_name'", "trace": "browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"78fba1e126965b39ac67f5656bb7b101\")>\n\n    @pytest.mark.usefixtures(\"browser\")\n    def test_login(browser):\n        logger.info('====== Started: {} ======'.format(int(time.time())))\n        try:\n            with allure.step('Navigating to Main Page and clicking My Account'):\n                logger.debug('Navigating to Main Page')\n                main_page = MainPage(browser)\n                logger.debug('Clicking My Account')\n                main_page.click_my_account()\n                take_screenshot(browser, 'Main Page - My Account')\n    \n            with allure.step('Clicking Register User'):\n                logger.debug('Clicking Register User')\n                main_page.click_register_user()\n                take_screenshot(browser, 'Main Page - Register User')\n    \n            with allure.step('Filling registration form'):\n                logger.debug('Filling registration form')\n                register_user = RegisterUser(browser)\n>               register_user.input_data_first_name()\nE               AttributeError: 'RegisterUser' object has no attribute 'input_data_first_name'\n\ntests/test_login.py:42: AttributeError"}, "steps": [{"name": "Navigating to Main Page and clicking My Account", "status": "passed", "attachments": [{"name": "Main Page - My Account", "source": "9765eb1c-e1d7-4ddc-a113-c4d61a35fe9e-attachment.png", "type": "image/png"}], "start": 1722155625735, "stop": 1722155626514}, {"name": "Clicking Register User", "status": "passed", "attachments": [{"name": "Main Page - Register User", "source": "c62d81e1-491d-4d7f-8547-aa9834851c2b-attachment.png", "type": "image/png"}], "start": 1722155626514, "stop": 1722155627377}, {"name": "Filling registration form", "status": "broken", "statusDetails": {"message": "AttributeError: 'RegisterUser' object has no attribute 'input_data_first_name'\n", "trace": "  File \"/home/we/Desktop/Projects/Python/pyOtus/tests/test_login.py\", line 42, in test_login\n    register_user.input_data_first_name()\n"}, "start": 1722155627377, "stop": 1722155627377}], "attachments": [{"name": "Error", "source": "814fbc19-5c9d-4411-824c-1f80ca79f9bb-attachment.png", "type": "image/png"}, {"name": "log", "source": "8a4a0097-c224-4cb7-b472-c4e2fbc4e455-attachment.txt", "type": "text/plain"}], "start": 1722155625735, "stop": 1722155627473, "uuid": "e4198220-163f-448d-8934-c8d25f94706e", "historyId": "a707b9555172d26c5c1ec2d556e674f3", "testCaseId": "a707b9555172d26c5c1ec2d556e674f3", "fullName": "tests.test_login#test_login", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('browser')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "we"}, {"name": "thread", "value": "6179-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}